### ISSUE TITLE
6.681版本为什么算出来的shield与抓包到的不一样呢？

### ISSUE THREAD

**Issue by 1789986088** [Sh4ww/cracking4crawling#1]
GET https://edith.xiaohongshu.com/api/sns/v10/search/notes?keyword=%E7%83%A4%E8%82%89&filters=%5B%5D&sort=time_descending&page=1&page_size=20&source=explore_feed&search_id=27x8e5hzo9j1qpu6muvb4%4027x8e8eqehow4uxq69pmo&session_id=27x8e42ravfm98ts7trls&api_extra=&page_pos=0&pin_note_id=&allow_rewrite=1&geo=eyJsYXRpdHVkZSI6MC4wMDAwMDAsImxvbmdpdHVkZSI6MC4wMDAwMDB9%0A&word_request_id=&clicked_card=&deviceId=e8c8ff79-f64b-3a9d-952a-9b02f1411f6a&identifier_flag=2&tz=Asia%2FShanghai&fid=1608793567107f7983ebbc9f4ac6c6898ffb5fde62ff&device_fingerprint1=20200403181150affdce7018cc5e0cfd065222465e13c8019895bc11bbdd9f&uis=light&launch_id=1608793567&device_fingerprint=20200403181150affdce7018cc5e0cfd065222465e13c8019895bc11bbdd9f&versionName=6.68.1&platform=android&sid=session.1608793629237544088475&t=1608793692&x_trace_page_current=search_result_notes&lang=zh-Hans&channel=Store360 HTTP/1.1
X-B3-TraceId: 9292de933b19080f
xy-common-params: deviceId=e8c8ff79-f64b-3a9d-952a-9b02f1411f6a&identifier_flag=2&tz=Asia%2FShanghai&fid=1608793567107f7983ebbc9f4ac6c6898ffb5fde62ff&device_fingerprint1=20200403181150affdce7018cc5e0cfd065222465e13c8019895bc11bbdd9f&uis=light&launch_id=1608793567&device_fingerprint=20200403181150affdce7018cc5e0cfd065222465e13c8019895bc11bbdd9f&versionName=6.68.1&platform=android&sid=session.1608793629237544088475&t=1608793692&x_trace_page_current=search_result_notes&lang=zh-Hans&channel=Store360
User-Agent: Dalvik/2.1.0 (Linux; U; Android 5.1.1; OPPO R11 Build/NMF26X) Resolution/720*1280 Version/6.68.1 Build/6681005 Device/(OPPO;OPPO R11) discover/6.68.1 NetType/WiFi
shield: edd22388425735bb1371d3fe2a0f8cdb
xy-platform-info: platform=android&build=6681005&deviceId=e8c8ff79-f64b-3a9d-952a-9b02f1411f6a
Host: edith.xiaohongshu.com
Connection: Keep-Alive
Accept-Encoding: gzip

算出来的结果是  f10c74a0eb6598d6fe7bf459df30448b

**Comment by Sh4ww** [comment]
你指的是"XYAAAAAQAAAAEAAABTAAAAUzUWEe0xG1IbD9/c+qCLOlKGmTtFa+lG43AJeOFXQ6RDxdfmmuRjRZ39/bRYz8Mu2Jl+2ao1QwxPRTHbN7Ly1SNlg+ObRDNNosbpaytVeCtgBoQp"这种格式的shield吗。
如果是的话，这种是最新更新的，目前还原的6.68.1的shield还是可以继续使用的。
如果不是，可能是你签名的方式有问题，可以提供一下请求头和参数，我看一下问题在哪。

**Comment by Sh4ww** [comment]
> 你指的是"XYAAAAAQAAAAEAAABTAAAAUzUWEe0xG1IbD9/c+qCLOlKGmTtFa+lG43AJeOFXQ6RDxdfmmuRjRZ39/bRYz8Mu2Jl+2ao1QwxPRTHbN7Ly1SNlg+ObRDNNosbpaytVeCtgBoQp"这种格式的shield吗。
> 如果是的话，这种是最新更新的，目前还原的6.68.1的shield还是可以继续使用的。
> 如果不是，可能是你签名的方式有问题，可以提供一下请求头和参数，我看一下问题在哪。

**Comment by 1789986088** [comment]
好的，我马上发上去------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Sh4ww&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月24日(星期四) 中午1:45
收件人:&nbsp;&quot;Sh4ww/cracking4crawling&quot;<cracking4crawling@noreply.github.com&gt;;
抄送:&nbsp;&quot;1789986088&quot;<1789986088@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Sh4ww/cracking4crawling] 6.681版本为什么算出来的shield与抓包到的不一样呢？ (#1)

**Comment by 1789986088** [comment]
你好，我这边在github上更新了请求头与这边算出来的结果，麻烦你看下为什么不一样，感谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Sh4ww&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月24日(星期四) 中午1:45
收件人:&nbsp;&quot;Sh4ww/cracking4crawling&quot;<cracking4crawling@noreply.github.com&gt;;
抄送:&nbsp;&quot;1789986088&quot;<1789986088@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Sh4ww/cracking4crawling] 6.681版本为什么算出来的shield与抓包到的不一样呢？ (#1)

**Comment by Sh4ww** [comment]
编码问题可能导致签名不一样，这个接口参数有点多我也不确定是哪个地方导致的签名不一样，但是你请求失败应该不是签名的问题，你的xy-common-params和xy-platform-info好像是用不了的，我换了这个两个参数之后是可以正常响应。

```python
from urllib import parse

import requests

from crawlers.xhs.lib.shield import get_sign
from crawlers.xhs.lib.shumei_slide_captcha import get_verify

params = {'keyword': 'zara', 'filters': '[]', 'sort': 'time_descending', 'page': '1', 'page_size': '20',
          'source': 'explore_feed', 'search_id': '',
          'session_id': '', 'api_extra': '', 'page_pos': '0', 'pin_note_id': '',
          'allow_rewrite': '1', 'geo': '',
          'word_request_id': '', 'clicked_card': ''}

xy_common_params = {
    'fid': '1605335236101e0d28eb076dacfe290f2edc95ed7d21',
    'device_fingerprint': '202011141057245b5a8f26510e7fd80a6a846eb03732900192dede8e36bb58',
    'device_fingerprint1': '202011141057245b5a8f26510e7fd80a6a846eb03732900192dede8e36bb58',
    'launch_id': '1606097486',
    'tz': 'Asia/Shanghai',
    'channel': 'YingYongBao',
    'versionName': '6.68.1',
    'deviceId': '10cf4b49-52d7-344d-887c-1ddcc9698557',
    'platform': 'android',
    'identifier_flag': '2',
    't': '1606098613',
    'x_trace_page_current': 'note_detail_r10',
    'lang': 'zh-Hans',
    'uis': 'light',
    'sid': 'session.1608793629237544088475'
}

xy_platform_info = {
    'platform': 'android',
    'build': '6681005',
    'deviceId': '10cf4b49-52d7-344d-887c-1ddcc9698557'
}

while True:
    rid, risk_level = get_verify('eR46sBuqF0fdw7KWFLYa')

    if risk_level == 'PASS':
        url = 'https://www.xiaohongshu.com/api/sns/v1/system_service/slide_captcha_check'

        data = {
            'pass': 'true',
            'from': 'native',
            'rid': rid
        }

        sign = get_sign(path='/' + '/'.join(url.split('/')[3:]), params=parse.urlencode(params),
                        xy_common_params=parse.urlencode(xy_common_params),
                        xy_platform_info=parse.urlencode(xy_platform_info), data=parse.urlencode(data))

        r = requests.post(url, data=data, headers={
            'xy-common-params': parse.urlencode(xy_common_params),
            'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 5.1.1; OPPO R11 Build/NMF26X) Resolution/720*1280 Version/6.68.1 Build/6681005 Device/(OPPO;OPPO R11) discover/6.68.1 NetType/WiFi',
            'shield': sign,
            'xy-platform-info': parse.urlencode(xy_platform_info)
        })

        print(r.text)
        break

url = 'https://edith.xiaohongshu.com/api/sns/v10/search/notes'

sign = get_sign(path='/' + '/'.join(url.split('/')[3:]), params=parse.urlencode(params),
                xy_common_params=parse.urlencode(xy_common_params),
                xy_platform_info=parse.urlencode(xy_platform_info))

r = requests.get(url, params=params, headers={
    'xy-common-params': parse.urlencode(xy_common_params),
    'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 5.1.1; OPPO R11 Build/NMF26X) Resolution/720*1280 Version/6.68.1 Build/6681005 Device/(OPPO;OPPO R11) discover/6.68.1 NetType/WiFi',
    'shield': sign,
    'xy-platform-info': parse.urlencode(xy_platform_info)
})

print(r.text)```

**Comment by 1789986088** [comment]
好的，多谢，是我这个apk的问题吗，能不能发下咱们那边的apk呢

**Comment by Sh4ww** [comment]
你指小红书的apk吗，我用的都是豌豆荚上的，有历史版本

**Comment by 1789986088** [comment]
> 你指小红书的apk吗，我用的都是豌豆荚上的，有历史版本

好的，感谢，我试试

**Comment by 1789986088** [comment]
> 你指小红书的apk吗，我用的都是豌豆荚上的，有历史版本

博主你好，能加下qq吗，我这边用你的可以，换我的就不可以了，想请教下 1789986088

**Comment by GuanFoxyier** [comment]
> 编码问题可能导致签名不一样，这个接口参数有点多我也不确定是哪个地方导致的签名不一样，但是你请求失败应该不是签名的问题，你的xy-common-params和xy-platform-info好像是用不了的，我换了这个两个参数之后是可以正常响应。
> 
> ```python
> from urllib import parse
> 
> import requests
> 
> from crawlers.xhs.lib.shield import get_sign
> from crawlers.xhs.lib.shumei_slide_captcha import get_verify
> 
> params = {'keyword': 'zara', 'filters': '[]', 'sort': 'time_descending', 'page': '1', 'page_size': '20',
>           'source': 'explore_feed', 'search_id': '',
>           'session_id': '', 'api_extra': '', 'page_pos': '0', 'pin_note_id': '',
>           'allow_rewrite': '1', 'geo': '',
>           'word_request_id': '', 'clicked_card': ''}
> 
> xy_common_params = {
>     'fid': '1605335236101e0d28eb076dacfe290f2edc95ed7d21',
>     'device_fingerprint': '202011141057245b5a8f26510e7fd80a6a846eb03732900192dede8e36bb58',
>     'device_fingerprint1': '202011141057245b5a8f26510e7fd80a6a846eb03732900192dede8e36bb58',
>     'launch_id': '1606097486',
>     'tz': 'Asia/Shanghai',
>     'channel': 'YingYongBao',
>     'versionName': '6.68.1',
>     'deviceId': '10cf4b49-52d7-344d-887c-1ddcc9698557',
>     'platform': 'android',
>     'identifier_flag': '2',
>     't': '1606098613',
>     'x_trace_page_current': 'note_detail_r10',
>     'lang': 'zh-Hans',
>     'uis': 'light',
>     'sid': 'session.1608793629237544088475'
> }
> 
> xy_platform_info = {
>     'platform': 'android',
>     'build': '6681005',
>     'deviceId': '10cf4b49-52d7-344d-887c-1ddcc9698557'
> }
> 
> while True:
>     rid, risk_level = get_verify('eR46sBuqF0fdw7KWFLYa')
> 
>     if risk_level == 'PASS':
>         url = 'https://www.xiaohongshu.com/api/sns/v1/system_service/slide_captcha_check'
> 
>         data = {
>             'pass': 'true',
>             'from': 'native',
>             'rid': rid
>         }
> 
>         sign = get_sign(path='/' + '/'.join(url.split('/')[3:]), params=parse.urlencode(params),
>                         xy_common_params=parse.urlencode(xy_common_params),
>                         xy_platform_info=parse.urlencode(xy_platform_info), data=parse.urlencode(data))
> 
>         r = requests.post(url, data=data, headers={
>             'xy-common-params': parse.urlencode(xy_common_params),
>             'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 5.1.1; OPPO R11 Build/NMF26X) Resolution/720*1280 Version/6.68.1 Build/6681005 Device/(OPPO;OPPO R11) discover/6.68.1 NetType/WiFi',
>             'shield': sign,
>             'xy-platform-info': parse.urlencode(xy_platform_info)
>         })
> 
>         print(r.text)
>         break
> 
> url = 'https://edith.xiaohongshu.com/api/sns/v10/search/notes'
> 
> sign = get_sign(path='/' + '/'.join(url.split('/')[3:]), params=parse.urlencode(params),
>                 xy_common_params=parse.urlencode(xy_common_params),
>                 xy_platform_info=parse.urlencode(xy_platform_info))
> 
> r = requests.get(url, params=params, headers={
>     'xy-common-params': parse.urlencode(xy_common_params),
>     'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 5.1.1; OPPO R11 Build/NMF26X) Resolution/720*1280 Version/6.68.1 Build/6681005 Device/(OPPO;OPPO R11) discover/6.68.1 NetType/WiFi',
>     'shield': sign,
>     'xy-platform-info': parse.urlencode(xy_platform_info)
> })
> 
> print(r.text)```
> ```

您好， 您代码中make_ctx函数的返回值是根据deviceId和其他的值一起进行aes计算出来的， 所以导致我们只能用您的deviceId才能请求成功，您有空的时候能分享一下make_ctx的动态生成办法么， 非常感谢！

**Comment by Sh4ww** [comment]
> > 编码问题可能导致签名不一样，这个接口参数有点多我也不确定是哪个地方导致的签名不一样，但是你请求失败应该不是签名的问题，你的xy-common-params和xy-platform-info好像是用不了的，我换了这个两个参数之后是可以正常响应。
> > ```python
> > from urllib import parse
> > 
> > import requests
> > 
> > from crawlers.xhs.lib.shield import get_sign
> > from crawlers.xhs.lib.shumei_slide_captcha import get_verify
> > 
> > params = {'keyword': 'zara', 'filters': '[]', 'sort': 'time_descending', 'page': '1', 'page_size': '20',
> >           'source': 'explore_feed', 'search_id': '',
> >           'session_id': '', 'api_extra': '', 'page_pos': '0', 'pin_note_id': '',
> >           'allow_rewrite': '1', 'geo': '',
> >           'word_request_id': '', 'clicked_card': ''}
> > 
> > xy_common_params = {
> >     'fid': '1605335236101e0d28eb076dacfe290f2edc95ed7d21',
> >     'device_fingerprint': '202011141057245b5a8f26510e7fd80a6a846eb03732900192dede8e36bb58',
> >     'device_fingerprint1': '202011141057245b5a8f26510e7fd80a6a846eb03732900192dede8e36bb58',
> >     'launch_id': '1606097486',
> >     'tz': 'Asia/Shanghai',
> >     'channel': 'YingYongBao',
> >     'versionName': '6.68.1',
> >     'deviceId': '10cf4b49-52d7-344d-887c-1ddcc9698557',
> >     'platform': 'android',
> >     'identifier_flag': '2',
> >     't': '1606098613',
> >     'x_trace_page_current': 'note_detail_r10',
> >     'lang': 'zh-Hans',
> >     'uis': 'light',
> >     'sid': 'session.1608793629237544088475'
> > }
> > 
> > xy_platform_info = {
> >     'platform': 'android',
> >     'build': '6681005',
> >     'deviceId': '10cf4b49-52d7-344d-887c-1ddcc9698557'
> > }
> > 
> > while True:
> >     rid, risk_level = get_verify('eR46sBuqF0fdw7KWFLYa')
> > 
> >     if risk_level == 'PASS':
> >         url = 'https://www.xiaohongshu.com/api/sns/v1/system_service/slide_captcha_check'
> > 
> >         data = {
> >             'pass': 'true',
> >             'from': 'native',
> >             'rid': rid
> >         }
> > 
> >         sign = get_sign(path='/' + '/'.join(url.split('/')[3:]), params=parse.urlencode(params),
> >                         xy_common_params=parse.urlencode(xy_common_params),
> >                         xy_platform_info=parse.urlencode(xy_platform_info), data=parse.urlencode(data))
> > 
> >         r = requests.post(url, data=data, headers={
> >             'xy-common-params': parse.urlencode(xy_common_params),
> >             'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 5.1.1; OPPO R11 Build/NMF26X) Resolution/720*1280 Version/6.68.1 Build/6681005 Device/(OPPO;OPPO R11) discover/6.68.1 NetType/WiFi',
> >             'shield': sign,
> >             'xy-platform-info': parse.urlencode(xy_platform_info)
> >         })
> > 
> >         print(r.text)
> >         break
> > 
> > url = 'https://edith.xiaohongshu.com/api/sns/v10/search/notes'
> > 
> > sign = get_sign(path='/' + '/'.join(url.split('/')[3:]), params=parse.urlencode(params),
> >                 xy_common_params=parse.urlencode(xy_common_params),
> >                 xy_platform_info=parse.urlencode(xy_platform_info))
> > 
> > r = requests.get(url, params=params, headers={
> >     'xy-common-params': parse.urlencode(xy_common_params),
> >     'user-agent': 'Dalvik/2.1.0 (Linux; U; Android 5.1.1; OPPO R11 Build/NMF26X) Resolution/720*1280 Version/6.68.1 Build/6681005 Device/(OPPO;OPPO R11) discover/6.68.1 NetType/WiFi',
> >     'shield': sign,
> >     'xy-platform-info': parse.urlencode(xy_platform_info)
> > })
> > 
> > print(r.text)```
> > ```
> 
> 您好， 您代码中make_ctx函数的返回值是根据deviceId和其他的值一起进行aes计算出来的， 所以导致我们只能用您的deviceId才能请求成功，您有空的时候能分享一下make_ctx的动态生成办法么， 非常感谢！

是的，我也发现这个问题了，我现在也在跟踪这个的生成，如果有进展，我会更新上来的。

**Comment by zhengcodeman** [comment]
请问/api/sns/v2/note/ 这个无水印接口计算出来的shield和抓包的对不上呢！

**Comment by Sh4ww** [comment]
> 请问/api/sns/v2/note/ 这个无水印接口计算出来的shield和抓包的对不上呢！

目前实现的有点不完整，只能对固定的deviceId签名，正在还原剩下部分，这几天会更新。

**Comment by zhengcodeman** [comment]
> > 请问/ api / sns / v2 / note /这个无水印接口计算出来的shield和抓包的对不上呢！
> 
> 目前实现的有点不完整，只能对固定的deviceId签名，正在还原剩下的部分，这几天会更新。

楼主能否加一下QQ：188801652，一起研究

**Comment by HCZHONG** [comment]
hmacmd5的key是使用 魔改的aes，已经还原。并且已经还原最新版的shield

**Comment by zhengcodeman** [comment]
> hmacmd5的key是使用 魔改的aes，已经还原。并且已经还原最新版的shield

请问源码在哪里呢？

**Comment by soul-cat** [comment]
> hmacmd5的key是使用 魔改的aes，已经还原。并且已经还原最新版的shield

刚还在看你得帖子

**Comment by Sh4ww** [comment]
已更新

**Comment by soul-cat** [comment]
> 已更新

感谢大佬的代码奉献，三连已给

**Comment by zhengcodeman** [comment]
> 已更新

大神，还是计算不对称哦！能不能给个案例

**Comment by Sh4ww** [comment]
> 
> 
> > 已更新
> 
> 大神，还是计算不对称哦！能不能给个案例

可以发一下你的请求和main_hmac吗

**Comment by zhengcodeman** [comment]
> > > 已更新
> > 
> > 
> > 大神，还是计算不对称哦！能不能给个案例
> 
> 可以发一下你的请求和main_hmac吗

main_hmac值不是固定的吗？


:method	GET
:path	/api/sns/v1/system_service/resource_list?version=6220111&tag=SwanWebViewSo&platform=android&deviceId=b5cb439a-4d65-3bc1-aa66-4ada469ffaab&device_fingerprint=2020121823282687d684032b634e3ed778eb62f1a7de92018e5595e47e6bad&device_fingerprint1=2020121823282687d684032b634e3ed778eb62f1a7de92018e5595e47e6bad&versionName=6.22.0&channel=Vivo&sid=&lang=zh-Hans&t=1609386871&fid=160938686810a4db074cee6740ae3b0bd2fd58f6adad&sign=0743974e47acbc006571f3137b937442
:authority	www.xiaohongshu.com
:scheme	https
xy-common-params	platform=android&deviceId=b5cb439a-4d65-3bc1-aa66-4ada469ffaab&device_fingerprint=2020121823282687d684032b634e3ed778eb62f1a7de92018e5595e47e6bad&device_fingerprint1=2020121823282687d684032b634e3ed778eb62f1a7de92018e5595e47e6bad&versionName=6.22.0&channel=Vivo&sid=&t=1609386871&fid=160938686810a4db074cee6740ae3b0bd2fd58f6adad
user-agent	Dalvik/2.1.0 (Linux; U; Android 5.1.1; M973Q Build/LMY48Z) Resolution/1080*1920 Version/6.22.0 Build/6220111 Device/(Meizu;M973Q) discover/6.22.0 NetType/WiFi
shield	588b10c1a99b19a535510fe7839894bb
xy-platform-info	platform=android&build=6220111&deviceId=b5cb439a-4d65-3bc1-aa66-4ada469ffaab
accept-encoding	gzip

您计算一下看得出来的是不是shield	588b10c1a99b19a535510fe7839894bb

**Comment by Sh4ww** [comment]
> 
> 
> > > > 已更新
> > > 
> > > 
> > > 大神，还是计算不对称哦！能不能给个案例
> > 
> > 
> > 可以发一下你的请求和main_hmac吗
> 
> main_hmac值不是固定的吗？
> 
> :method GET
> :path /api/sns/v1/system_service/resource_list?version=6220111&tag=SwanWebViewSo&platform=android&deviceId=b5cb439a-4d65-3bc1-aa66-4ada469ffaab&device_fingerprint=2020121823282687d684032b634e3ed778eb62f1a7de92018e5595e47e6bad&device_fingerprint1=2020121823282687d684032b634e3ed778eb62f1a7de92018e5595e47e6bad&versionName=6.22.0&channel=Vivo&sid=&lang=zh-Hans&t=1609386871&fid=160938686810a4db074cee6740ae3b0bd2fd58f6adad&sign=0743974e47acbc006571f3137b937442
> :authority [www.xiaohongshu.com](http://www.xiaohongshu.com)
> :scheme https
> xy-common-params platform=android&deviceId=b5cb439a-4d65-3bc1-aa66-4ada469ffaab&device_fingerprint=2020121823282687d684032b634e3ed778eb62f1a7de92018e5595e47e6bad&device_fingerprint1=2020121823282687d684032b634e3ed778eb62f1a7de92018e5595e47e6bad&versionName=6.22.0&channel=Vivo&sid=&t=1609386871&fid=160938686810a4db074cee6740ae3b0bd2fd58f6adad
> user-agent Dalvik/2.1.0 (Linux; U; Android 5.1.1; M973Q Build/LMY48Z) Resolution/1080*1920 Version/6.22.0 Build/6220111 Device/(Meizu;M973Q) discover/6.22.0 NetType/WiFi
> shield 588b10c1a99b19a535510fe7839894bb
> xy-platform-info platform=android&build=6220111&deviceId=b5cb439a-4d65-3bc1-aa66-4ada469ffaab
> accept-encoding gzip
> 
> 您计算一下看得出来的是不是shield 588b10c1a99b19a535510fe7839894bb

main_hmac是每个设备都不同的，跟deviceId关联，readme里有写在哪去看这个值，这个值不对后面计算自然不会对

**Comment by zhengcodeman** [comment]
> > > 已更新
> > 
> > 
> > 大神，还是计算不对称哦！能不能给个案例
> 
> 可以发一下你的请求和main_hmac吗

<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="main">6eae07322d291614</string>
</map>
我在DATA/..../S.XML找到的值和您的不太一样哦

**Comment by Sh4ww** [comment]
> 
> 
> > > > 已更新
> > > 
> > > 
> > > 大神，还是计算不对称哦！能不能给个案例
> > 
> > 
> > 可以发一下你的请求和main_hmac吗
> 
> 6eae07322d291614 我在DATA/..../S.XML找到的值和您的不太一样哦

你是6.681版本的吗，这个应该是128位的

**Comment by zhengcodeman** [comment]
> > > > > 已更新
> > > > 
> > > > 
> > > > 大神，还是计算不对称哦！能不能给个案例
> > > 
> > > 
> > > 可以发一下你的请求和main_hmac吗
> > 
> > 
> > 6eae07322d291614 我在DATA/..../S.XML找到的值和您的不太一样哦
> 
> 你是6.681版本的吗，这个应该是128位的

我的是6.22.0版本·6.681没办法反编译·我去找一个6.681版本下去

**Comment by zhengcodeman** [comment]
> > > > > > 已更新
> > > > > 
> > > > > 
> > > > > 大神，还是计算不对称哦！能不能给个案例
> > > > 
> > > > 
> > > > 可以发一下你的请求和main_hmac吗
> > > 
> > > 
> > > 6eae07322d291614 我在DATA/..../S.XML找到的值和您的不太一样哦
> > 
> > 
> > 你是6.681版本的吗，这个应该是128位的
> 
> 我的是6.22.0版本·6.681没办法反编译·我去找一个6.681版本下去

+IyF1PPCbS3ymPipAI1//S0dLQzBsrQAhqC6NmhxpjvzCJ14kERTqsFwJXD/uXcmltb57GHX140kT19IXPCTQCUgq4XNYrmyDCvsLDGXGqmMftvk5vnnZL8/79eoHr/L
这下对了

**Comment by Sh4ww** [comment]
> 
> 
> > > > > > > 已更新
> > > > > > 
> > > > > > 
> > > > > > 大神，还是计算不对称哦！能不能给个案例
> > > > > 
> > > > > 
> > > > > 可以发一下你的请求和main_hmac吗
> > > > 
> > > > 
> > > > 6eae07322d291614 我在DATA/..../S.XML找到的值和您的不太一样哦
> > > 
> > > 
> > > 你是6.681版本的吗，这个应该是128位的
> > 
> > 
> > 我的是6.22.0版本·6.681没办法反编译·我去找一个6.681版本下去
> 
> +IyF1PPCbS3ymPipAI1//S0dLQzBsrQAhqC6NmhxpjvzCJ14kERTqsFwJXD/uXcmltb57GHX140kT19IXPCTQCUgq4XNYrmyDCvsLDGXGqmMftvk5vnnZL8/79eoHr/L
> 这下对了

再抓一个这个版本的包吧

**Comment by zhengcodeman** [comment]
> > > 已更新
> > 
> > 
> > 大神，还是计算不对称哦！能不能给个案例
> 
> 可以发一下你的请求和main_hmac吗

大神什么时候研究新的shield

**Comment by Sh4ww** [comment]
> > > > 已更新
> > > 
> > > 
> > > 大神，还是计算不对称哦！能不能给个案例
> > 
> > 
> > 可以发一下你的请求和main_hmac吗
> 
> 大神什么时候研究新的shield

点个star吧，后面有时间会去看的
